decoration {
    active_opacity = 0.85
    inactive_opacity = 0.65
    blur {
        enabled = true
        size = 5
        passes = 2
        new_optimizations = true
        xray = false
        noise = 0.03
    }
    shadow {
        enabled = false
    }
    dim_inactive = true
    dim_strength = 0.05
}

animations {
    enabled = true
    bezier = instant, 0, 1, 0, 1
    animation = windowsIn, 1, 1, instant, popin 90%
    animation = windowsOut, 1, 1, instant, popin 90%
    animation = fadeIn, 1, 1, instant
    animation = fadeOut, 1, 1, instant
    animation = windowsMove, 1, 1, instant, slide
    animation = workspaces, 1, 1, instant, slide
    animation = layersIn, 1, 1, instant, popin 95%
    animation = layersOut, 1, 1, instant, popin 95%
}
