# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1

# Window transparency
windowrule = opacity 0.85 override 0.65 override, match:class .*
windowrule = opacity 1.0 override 0.85 override, match:class Zen Browser
windowrule = border_color rgb(00a0f4), match:class .*

layerrule = blur 1, match:namespace ironbar


# Workspace 1 = terminal only
windowrule = match:class kitty, workspace 1
windowrule = match:class negative:kitty, match:workspace 1, workspace 2
